package ch.psi.jstriptool;

import javax.swing.JDialog;

/**
 *
 */
public class DialogAbout extends JDialog {

    public DialogAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        textVersion.setText(App.getApplicationVersion());
        getRootPane().setDefaultButton(buttonClose);
        pack();
    }

    public void closeAboutBox() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelMail = new javax.swing.JLabel();
        textMailUser = new javax.swing.JLabel();
        labelAppDesc = new javax.swing.JLabel();
        textMailDomain = new javax.swing.JLabel();
        labelAppTitle = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();
        labelFeedback = new javax.swing.JLabel();
        textVersion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonClose = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel2.setName("jPanel2"); // NOI18N

        labelMail.setText("@");
        labelMail.setName("labelMail"); // NOI18N

        textMailUser.setText("alexandre.gobbo");
        textMailUser.setName("textMailUser"); // NOI18N

        labelAppDesc.setText("Java reimplementation of StripTool (https://epics.anl.gov/extensions/StripTool)");
        labelAppDesc.setName("labelAppDesc"); // NOI18N

        textMailDomain.setText("psi.ch");
        textMailDomain.setName("textMailDomain"); // NOI18N

        labelAppTitle.setFont(labelAppTitle.getFont().deriveFont(labelAppTitle.getFont().getStyle() | java.awt.Font.BOLD, labelAppTitle.getFont().getSize()+4));
        labelAppTitle.setText("JStripTool");
        labelAppTitle.setName("labelAppTitle"); // NOI18N

        labelVersion.setFont(labelVersion.getFont().deriveFont(labelVersion.getFont().getStyle() | java.awt.Font.BOLD));
        labelVersion.setText("Version:");
        labelVersion.setName("labelVersion"); // NOI18N

        labelFeedback.setFont(labelFeedback.getFont().deriveFont(labelFeedback.getFont().getStyle() | java.awt.Font.BOLD));
        labelFeedback.setText("Feedback:");
        labelFeedback.setName("labelFeedback"); // NOI18N

        textVersion.setName("textVersion"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelAppDesc)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelFeedback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textMailUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMailDomain))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelVersion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192))))
                    .addComponent(labelAppTitle))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelFeedback, labelVersion});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAppTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAppDesc)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFeedback)
                    .addComponent(textMailDomain)
                    .addComponent(textMailUser)
                    .addComponent(labelMail))
                .addGap(28, 28, 28))
        );

        jPanel1.setName("jPanel1"); // NOI18N

        buttonClose.setText("Ok");
        buttonClose.setName("buttonClose"); // NOI18N
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        labelImage.setName("labelImage"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelImage)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonClose, labelImage});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonClose)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        closeAboutBox();
}//GEN-LAST:event_buttonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton buttonClose;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JLabel labelAppDesc;
    javax.swing.JLabel labelAppTitle;
    javax.swing.JLabel labelFeedback;
    javax.swing.JLabel labelImage;
    javax.swing.JLabel labelMail;
    javax.swing.JLabel labelVersion;
    javax.swing.JLabel textMailDomain;
    javax.swing.JLabel textMailUser;
    javax.swing.JLabel textVersion;
    // End of variables declaration//GEN-END:variables

}
