#!/bin/sh

# Find the latest Java in /usr/lib/jvm/
#JAVA_HOME=\$(ls -d /usr/lib/jvm/jre-* 2>/dev/null | sort -V | tail -n 1)
# Find the latest Java version (11+), ignoring Java 8 (`jre-openjdk`)
JAVA_HOME=\$(ls -d /usr/lib/jvm/jre-* 2>/dev/null | grep -E 'jre-[1-9][1-9]' | sort -V | tail -n 1)


# If JAVA_HOME is found, use its java binary; otherwise, fall back to system java
if [ -x "\$JAVA_HOME/bin/java" ]; then
    JAVA_CMD="\$JAVA_HOME/bin/java"
else
    JAVA_CMD="java"
fi

# Run the JAR with all passed arguments
exec "\$JAVA_CMD" -jar ${jar_file} "\$@"
